### ISSUE TITLE
Automatically delete the App from AppGroup

### ISSUE THREAD

**Issue by rzulkarn** [nextensio/tickets#1]
Deleting an App does not delete the app name in the AppGroup. 

Recommendations:
1. pop up a warning that the app is part of an AppGroup
2. delete the app automatically from the AppGroup

Steps to reproduce:
1. Create an App from the App Tab
2. Create a new AppGroup, include the App as part of the AppGroup
3. Delete the App from the App Tab
4. Go back to AppGroup tab, notice the deleted App remains

**Comment by gopakumarce** [comment]
Thx for the issue @rzulkarn .. This has been fixed in the latest UX as you can see when you login
