### ISSUE TITLE
Command-line support for connector image

### ISSUE THREAD

**Issue by greg-next** [nextensio/tickets#3]
Please add support for the following command-line options on the connector image.

1. -V, --version (to indicate which version of the connector the user is running
2. --help (to list the available command line options)

**Comment by gopakumarce** [comment]
Thx @greg-next - so the --help option already exists, its just -h  .. The -v option is a nice suggestion, we will add it, thanks!

**Comment by gopakumarce** [comment]
@greg-next has confirmed this is fixed
